### ISSUE TITLE
Issue new release

### ISSUE THREAD

**Issue by seandilda** [ruby/resolv#12]
Since #9 was merged, the master branch now contains a critical bug fix that has been breaking several applications.  

Unfortunately, the only real fixes right now are to back-rev your ruby version, or follow the instructions in https://github.com/mperham/sidekiq/issues/2175#issuecomment-841026801 and run a copy of this gem from github.

It'd be wonderful if a new rev of this gem could be published to rubygems.org so that users can use an official release to fix this issue.

**Comment by hsbt** [comment]
Just released resolv-0.2.1.

But this version was enabled only Ruby 3.0+.

**Comment by tonywok** [comment]
@hsbt Are there any guarantees around compatibility with older rubies? For instance, I'm interested in using resolv 0.2.1 in both ruby 2.6.5 an 2.7.3 😅
